apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gotli
spec:
  replicas: ${app_instance_replicas}
  template:
    metadata:
      labels:
        app: gotli
    spec:
      containers:
      - name: gotli
        image: ${image_uri}
        ports:
        - containerPort: ${app_container_port}
---
apiVersion: v1
kind: Service
metadata:
  name: gotli
  labels:
    app: gotli
spec:
  ports:
  - port: 80
    targetPort: ${app_container_port}
    protocol: TCP
    name: http
  selector:
    app: gotli
  type: LoadBalancer
