apiVersion: v1
kind: Namespace
metadata:
  name: federation-system
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: federation-apiserver-etcd
  annotations:
    volume.alpha.kubernetes.io/storage-class: "yes"
  namespace: federation-system
  labels:
    app: federated-cluster
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: federation-apiserver
  namespace: federation-system
  labels:
    app: federated-cluster
spec:
  template:
    metadata:
      name: federation-apiserver
      labels:
        app: federated-cluster
        module: federation-apiserver
    spec:
      containers:
      - name: apiserver
        image: gcr.io/google_containers/hyperkube:v${kubernetes_version}
        command:
          - /hyperkube
          - federation-apiserver
          - --bind-address=0.0.0.0
          - --etcd-servers=http://localhost:2379
          - --secure-port=443
          - --advertise-address=${k8s_master_ip}
          - --service-cluster-ip-range=10.10.0.0/24
          - --token-auth-file=/etc/kubernetes/known_tokens.csv
        ports:
          - containerPort: 443
            name: https
          - containerPort: 8080
            name: local
        volumeMounts:
          - name: federation-apiserver-secrets
            mountPath: /etc/kubernetes/
            readOnly: true
      - name: etcd
        image: quay.io/coreos/etcd:v3.0.7
        command:
          - "/usr/local/bin/etcd"
        args:
          - "--data-dir=/var/lib/etcd"
        volumeMounts:
          - name: etcd-data
            mountPath: /var/lib/etcd
      volumes:
        - name: federation-apiserver-secrets
          secret:
            secretName: federation-apiserver-secrets
        - name: etcd-data
          persistentVolumeClaim:
            claimName: federation-apiserver-etcd
---
apiVersion: v1
kind: Service
metadata:
  name: federation-apiserver
  namespace: federation-system
  labels:
    app: federated-cluster
spec:
  type: LoadBalancer
  selector:
    app: federated-cluster
    module: federation-apiserver
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: federation-controller-manager
  namespace: federation-system
  labels:
    app: federated-cluster
spec:
  template:
    metadata:
      name: federation-controller-manager
      labels:
        app: federated-cluster
        module: federation-controller-manager
    spec:
      volumes:
      - name: ssl
        hostPath:
          path: /etc/ssl
      containers:
      - name: controller-manager
        image: gcr.io/google_containers/hyperkube:v${kubernetes_version}
        args:
          - /hyperkube
          - federation-controller-manager
          - --master=https://federation-apiserver.federation-system.svc.cluster.local
          - --dns-provider=aws-route53
          - --federation-name=federation-cluster
          - --zone-name=${aws_public_zone}
          - --v=2
        volumeMounts:
        - name: ssl
          readOnly: true
          mountPath: /etc/ssl
        ports:
          - containerPort: 443
            name: https
          - containerPort: 8080
            name: local
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
